### ISSUE TITLE
Typo in DataAcquisition OBO context file

### ISSUE THREAD

**Issue by jonathancrabtree** [datatagsuite/context#4]
Small typo ("DataAcquistion") in DataAcquisition OBO context file causing SDO type for the entity to take precedence:

https://github.com/datatagsuite/context/blob/cc702ab681c5113a76883718346ad0d71e610384/obo/data_acquisition_obo_context.jsonld#L6

**Comment by agbeltran** [comment]
Thank you @jonathancrabtree - now fixed.
